name: release

on:
  push:
    branches:
      - return
#    tags:
#      - v*
  pull_request:
    branches:
      - return

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.6.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install
      
      - name: build
        run: pnpm build
      
      - name: deploy
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
